# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FormalLetter.ui'
#
# Created: Tue Mar 18 15:06:32 2014
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(645, 585)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setGeometry(QtCore.QRect(0, 330, 651, 16))
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.subjectLineEdit = QtGui.QLineEdit(Dialog)
        self.subjectLineEdit.setGeometry(QtCore.QRect(280, 310, 331, 21))
        self.subjectLineEdit.setObjectName(_fromUtf8("subjectLineEdit"))
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 150, 111, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setGeometry(QtCore.QRect(30, 390, 111, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.dateLineEdit = QtGui.QLineEdit(Dialog)
        self.dateLineEdit.setGeometry(QtCore.QRect(280, 270, 331, 21))
        self.dateLineEdit.setObjectName(_fromUtf8("dateLineEdit"))
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(30, 350, 111, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.sendAddr3LineEdit = QtGui.QLineEdit(Dialog)
        self.sendAddr3LineEdit.setGeometry(QtCore.QRect(280, 100, 331, 21))
        self.sendAddr3LineEdit.setObjectName(_fromUtf8("sendAddr3LineEdit"))
        self.label = QtGui.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(220, 10, 141, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.pushButton = QtGui.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(260, 510, 75, 23))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.contentLineEdit = QtGui.QLineEdit(Dialog)
        self.contentLineEdit.setGeometry(QtCore.QRect(280, 390, 331, 21))
        self.contentLineEdit.setReadOnly(True)
        self.contentLineEdit.setObjectName(_fromUtf8("contentLineEdit"))
        self.line_5 = QtGui.QFrame(Dialog)
        self.line_5.setGeometry(QtCore.QRect(0, 370, 651, 16))
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setGeometry(QtCore.QRect(0, 250, 651, 16))
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.line_8 = QtGui.QFrame(Dialog)
        self.line_8.setGeometry(QtCore.QRect(-10, 490, 651, 16))
        self.line_8.setFrameShape(QtGui.QFrame.HLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.sendNameLineEdit = QtGui.QLineEdit(Dialog)
        self.sendNameLineEdit.setGeometry(QtCore.QRect(280, 470, 331, 21))
        self.sendNameLineEdit.setObjectName(_fromUtf8("sendNameLineEdit"))
        self.line_6 = QtGui.QFrame(Dialog)
        self.line_6.setGeometry(QtCore.QRect(0, 410, 651, 16))
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 190, 111, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(30, 430, 111, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.salutationLineEdit = QtGui.QLineEdit(Dialog)
        self.salutationLineEdit.setGeometry(QtCore.QRect(280, 350, 331, 21))
        self.salutationLineEdit.setObjectName(_fromUtf8("salutationLineEdit"))
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setGeometry(QtCore.QRect(0, 290, 651, 16))
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.regardsLineEdit = QtGui.QLineEdit(Dialog)
        self.regardsLineEdit.setGeometry(QtCore.QRect(280, 430, 331, 21))
        self.regardsLineEdit.setObjectName(_fromUtf8("regardsLineEdit"))
        self.recvAddr2LineEdit = QtGui.QLineEdit(Dialog)
        self.recvAddr2LineEdit.setGeometry(QtCore.QRect(280, 200, 331, 21))
        self.recvAddr2LineEdit.setObjectName(_fromUtf8("recvAddr2LineEdit"))
        self.recvAddr1LineEdit = QtGui.QLineEdit(Dialog)
        self.recvAddr1LineEdit.setGeometry(QtCore.QRect(280, 170, 331, 21))
        self.recvAddr1LineEdit.setObjectName(_fromUtf8("recvAddr1LineEdit"))
        self.sendAddr2LineEdit = QtGui.QLineEdit(Dialog)
        self.sendAddr2LineEdit.setGeometry(QtCore.QRect(280, 70, 331, 21))
        self.sendAddr2LineEdit.setObjectName(_fromUtf8("sendAddr2LineEdit"))
        self.recvNameLineEdit = QtGui.QLineEdit(Dialog)
        self.recvNameLineEdit.setGeometry(QtCore.QRect(280, 140, 331, 21))
        self.recvNameLineEdit.setObjectName(_fromUtf8("recvNameLineEdit"))
        self.recvAddr3LineEdit = QtGui.QLineEdit(Dialog)
        self.recvAddr3LineEdit.setGeometry(QtCore.QRect(280, 230, 331, 21))
        self.recvAddr3LineEdit.setObjectName(_fromUtf8("recvAddr3LineEdit"))
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(30, 310, 111, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(30, 270, 111, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 50, 111, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.line = QtGui.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 120, 651, 16))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.label_10 = QtGui.QLabel(Dialog)
        self.label_10.setGeometry(QtCore.QRect(30, 470, 111, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.line_7 = QtGui.QFrame(Dialog)
        self.line_7.setGeometry(QtCore.QRect(0, 450, 651, 16))
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.sendAddr1LineEdit = QtGui.QLineEdit(Dialog)
        self.sendAddr1LineEdit.setGeometry(QtCore.QRect(280, 40, 331, 21))
        self.sendAddr1LineEdit.setObjectName(_fromUtf8("sendAddr1LineEdit"))

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Addressee</span></p></body></html>", None))
        self.label_8.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Content</span></p></body></html>", None))
        self.label_7.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Salutation</span></p></body></html>", None))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:11pt; font-weight:600;\">FORMAL LETTER</span></p></body></html>", None))
        self.pushButton.setText(_translate("Dialog", "Proceed", None))
        self.contentLineEdit.setText(_translate("Dialog", "-to be filled later-", None))
        self.label_4.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Receiver\'s Address</span></p></body></html>", None))
        self.label_9.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Regards</span></p></body></html>", None))
        self.sendAddr2LineEdit.setText(_translate("Dialog", "Line 2", None))
        self.label_6.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Subject</span></p></body></html>", None))
        self.label_5.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Date</span></p></body></html>", None))
        self.label_2.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-size:9pt; font-weight:600;\">Sender\'s Address</span></p></body></html>", None))
        self.label_10.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Sender\'s Name</span></p></body></html>", None))
        self.sendAddr1LineEdit.setText(_translate("Dialog", "Line 1", None))

